# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-service
#services:
#  - mysql:latest
#  - redis:latest
#  - postgres:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

#test_async:
#  script:
#   - npm install
#   - node ./specs/start.js ./specs/async.spec.js

#test_db:
#  script:
#   - npm install
#   - node ./specs/start.js ./specs/db-postgres.spec.js
install:
  script:
   - echo $CI_PROJECT_DIR
   - npm install &> npm.log
#   - npm rebuild node-sass --force
#   - ng build --bh /dashboard-client/ -prod &> ng.log
   - ng build --bh /dashboard-client/ --env=dev1 &> ng.log
   - /home/gitlab-runner/energy-dashboard-client_deploy.sh $CI_PROJECT_DIR/dist
  only:
   - master

  artifacts:
    paths:
    - npm.log
    - ng.log
    - dist
    when: always
